{{ $attendees := (add1 .Values.attendees | int) }}
{{- range $attendee := untilStep 1 $attendees 1 }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: user{{ $attendee }}-registry-db-parameters
  namespace: user{{ $attendee }}-jukebox
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
  MYSQL_DATABASE: metadb
  MYSQL_PORT: '3306'
{{- end }}