{{ $attendees := (add1 .Values.attendees | int) }}
{{- range $attendee := untilStep 1 $attendees 1 }}
---
kind: Secret
apiVersion: v1
metadata:
  name: user{{ $attendee }}-registry-db-secrets
  namespace: user{{ $attendee }}-jukebox
data:
  MYSQL_ROOT_PASSWORD: dGVzdA==
  MYSQL_USER_NAME: cm9vdA==
type: Opaque
{{- end }}