---
apiVersion: pfe.rhpds.com/v1
kind: Gitea
metadata:
  name: gitea
  namespace: gitea
spec:
  giteaImageTag: 1.20.0
  giteaVolumeSize: 4Gi
  giteaSsl: true
  postgresqlVolumeSize: 20Gi
  giteaAdminUser: opentlc-mgr
  giteaAdminEmail: opentlc-mgr@redhat.com
  giteaAdminPasswordSecretName: gitea-admin-password
  giteaCreateUsers: true
  giteaUserNumber: {{ .Values.attendees }}
  {{- if eq (int .Values.attendees) 1 }}
  giteaGenerateUserFormat: "user1"
  {{- else}}
  giteaGenerateUserFormat: "user%d"
  {{- end }}
  giteaUserPasswordSecretName: gitea-user-password
  giteaMigrateRepositories: true
  giteaRepositoriesList:
  - repo: https://github.com/rhoai-mlops/jukebox.git
    name: jukebox
    private: true
  - repo: https://github.com/rhoai-mlops/mlops-helmcharts.git
    name: mlops-helmcharts
    private: true
  - repo: https://github.com/rhoai-mlops/mlops-gitops.git
    name: mlops-gitops
    private: true
  - repo: https://github.com/rhoai-mlops/jukebox-ui.git 
    name: jukebox-ui
    private: true