{{ $attendees := (add1 .Values.attendees | int) }}
{{- range $attendee := untilStep 1 $attendees 1 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: feast
  namespace: user{{ $attendee }}-jukebox
  labels:
    app: feature-store
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
{{- end }}